
package JDVISTAS;

import CONEXION.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class JD_turnos_ocupados extends javax.swing.JDialog {
    DefaultTableModel modelo;
    public JD_turnos_ocupados(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modeloTabla();
        consultar_turnos();
    }

    private void modeloTabla(){
        String[] columnaNombre = {"Turno","Marca","Placa","Propietario", "Empleado Asignado","Descripcion Servicio","Fecha", "Hora"};
        modelo.setColumnIdentifiers(columnaNombre);
        modelo.setColumnCount(8);
        modelo.setRowCount(0);
        tblTurnosOcupados.setModel(modelo);        
    }
    
    public void consultar_turnos() throws SQLException{
        Conexion con = new Conexion();
        ResultSet res;
        int linea=0;
        String query = "select ag.codigo_turno, veh.marca,veh.numero_placa, veh.propietario, \n" +
                "concat(em.Nombre ,' ' ,em.apellido) as empleado,ser.descripcion ,ag.fecha, ag.hora from agenda ag \n" +
                "join vehiculo veh on ag.codigo_vehiculo = veh.codigo_vehiculo join empleado em on ag.codigo_empleado = em.codigo_empleado \n" +
                "join servicio ser on ag.codigo_servicio = ser.codigo_servicio"; 
        res = con.EjecutarConsulta(query);
        DefaultTableModel modelo = (DefaultTableModel) tblTurnosOcupados.getModel();
        Object nuevo[] = {modelo.getRowCount() + 1,"",""};
        while (res.next()){    
        modelo.addRow(nuevo);
        tblTurnosOcupados.setValueAt(res.getInt(1),linea,0);
        tblTurnosOcupados.setValueAt(res.getString(2),linea,1);
        tblTurnosOcupados.setValueAt(res.getString(3),linea,2);
        tblTurnosOcupados.setValueAt(res.getString(4),linea,3);
        tblTurnosOcupados.setValueAt(res.getString(5),linea,4);
        tblTurnosOcupados.setValueAt(res.getString(6),linea,5);
        tblTurnosOcupados.setValueAt(res.getString(7),linea,6);
        tblTurnosOcupados.setValueAt(res.getString(8),linea,7);
        linea++;
        
        }  
        con.CerrarConexion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurnosOcupados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTurnosOcupados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTurnosOcupados);

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1516, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       JD_inicio ventana2 = new JD_inicio(null, true);
       ventana2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_turnos_ocupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_turnos_ocupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_turnos_ocupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_turnos_ocupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JD_turnos_ocupados dialog = new JD_turnos_ocupados(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JD_turnos_ocupados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTurnosOcupados;
    // End of variables declaration//GEN-END:variables
}
